import { useLocation, useParams, Link } from "react-router-dom";
import { ArrowLeft, Calendar, Clock, User } from "lucide-react";
import { useEffect, useState } from "react";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { useToast } from "@/hooks/use-toast";
import NotFound from "./NotFound";
import BookCallModal from "@/components/BookCallModal";
import BlogKeywordDensity from "@/components/BlogKeywordDensity";

interface ArticleData {
  title: string;
  content: string;
  created_at?: string;
}

const ArticleDetail = () => {
  const { articleSlug } = useParams<{ articleSlug: string }>();
  const location = useLocation();
  const { toast } = useToast();
  const [articleData, setArticleData] = useState<ArticleData | null>(null);

  useEffect(() => {
    window.scrollTo(0, 0);
    
    // Check if we have article data from navigation state
    if (location.state && location.state.blogTitle && location.state.blogContent) {
      setArticleData({
        title: location.state.blogTitle,
        content: location.state.blogContent,
        created_at: location.state.created_at
      });
    }
  }, [location.state]);



  const formatDate = (dateString?: string) => {
    if (!dateString) return new Date().toLocaleDateString();
    try {
      return new Date(dateString).toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'long',
        day: 'numeric'
      });
    } catch {
      return new Date().toLocaleDateString();
    }
  };

  // Function to extract text content from HTML for keyword analysis
  const extractTextFromHTML = (html: string): string => {
    const tempDiv = document.createElement('div');
    tempDiv.innerHTML = html;
    return tempDiv.textContent || tempDiv.innerText || '';
  };

  // If no article data, show 404 or loading state
  if (!articleData) {
    return <NotFound />;
  }

  return (
    <div className="min-h-screen">
      <Navbar />
      <main className="pt-20">
        {/* Header Section */}
        <section className="bg-gray-50 py-8 md:py-12">
          <div className="container-custom">
            <Link
              to="/portfolio/articles"
              className="inline-flex items-center text-gray-600 hover:text-gray-900 mb-6"
            >
              <ArrowLeft className="mr-2 h-4 w-4" /> Back to All Articles
            </Link>
            
            <div className="max-w-4xl">
              <div className="flex items-center gap-4 text-sm text-gray-600 mb-4">
                <div className="flex items-center gap-1">
                  <Calendar className="h-4 w-4" />
                  <span>{formatDate(articleData.created_at)}</span>
                </div>
                <div className="flex items-center gap-1">
                  <Clock className="h-4 w-4" />
                  <span>5 min read</span>
                </div>
                <div className="flex items-center gap-1">
                  <User className="h-4 w-4" />
                  <span>AI Generated</span>
                </div>
              </div>
              
              <h1 className="text-3xl md:text-5xl font-bold mb-6 text-gray-900">
                {articleData.title}
              </h1>
              
              <div className="text-sm text-gray-600">
                Generated by Small Group's AI Blog Writer
              </div>
            </div>
          </div>
        </section>

        {/* Article Content */}
        <section className="py-8 md:py-12">
          <div className="container-custom">
            <div className="max-w-7xl mx-auto">
              <div className="grid grid-cols-1 lg:grid-cols-6 gap-8">
                {/* Main Article Content */}
                <div className="lg:col-span-4">
                  <article className="prose prose-lg max-w-none">
                    <div 
                      dangerouslySetInnerHTML={{ __html: articleData.content }}
                      className="blog-content"
                    />
                  </article>
                </div>
                
                {/* Keyword Density Sidebar */}
                <div className="lg:col-span-2">
                  <div className="sticky top-24">
                    <BlogKeywordDensity 
                      content={extractTextFromHTML(articleData.content)}
                      className="mb-6"
                    />
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        <section className="py-12 bg-black from-brand-purple to-brand-blue text-white">
          <div className="container-custom text-center">
            <h2 className="text-2xl md:text-3xl font-bold mb-4">
              Impressed by This AI-Generated Content?
            </h2>
            <p className="text-lg mb-8 max-w-2xl mx-auto opacity-90">
              This article was automatically generated by our SEO Blog Writer system. 
              Want to see how we can automate content creation for your business?
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Link
                to="/portfolio/articles"
                className="inline-flex items-center justify-center px-6 py-3 bg-white text-black font-medium rounded-lg"
              >
                View More Articles
              </Link>
              <BookCallModal>
                <button className="inline-flex items-center justify-center px-6 py-3 bg-transparent border-2 border-white text-white font-medium rounded-lg">
                  Book a Discovery Call
                </button>
              </BookCallModal>
            </div>
          </div>
        </section>
      </main>
      <Footer />
    </div>
  );
};

export default ArticleDetail; 