import { useLocation, useParams, Link } from "react-router-dom";
import { ArrowLeft, Share2, Calendar, Clock, User } from "lucide-react";
import { useEffect, useState } from "react";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Button } from "@/components/ui/button";
import { useToast } from "@/hooks/use-toast";
import NotFound from "./NotFound";

interface BlogData {
  blogTitle: string;
  blogContent: string;
}

const BlogPost = () => {
  const { blogSlug } = useParams<{ blogSlug: string }>();
  const location = useLocation();
  const { toast } = useToast();
  const [blogData, setBlogData] = useState<BlogData | null>(null);

  useEffect(() => {
    window.scrollTo(0, 0);
    
    // Check if we have blog data from navigation state
    if (location.state && location.state.blogTitle && location.state.blogContent) {
      setBlogData({
        blogTitle: location.state.blogTitle,
        blogContent: location.state.blogContent
      });
    }
  }, [location.state]);

  const handleShare = async () => {
    if (navigator.share) {
      try {
        await navigator.share({
          title: blogData?.blogTitle || 'SEO Blog Post',
          text: 'Check out this AI-generated SEO blog post',
          url: window.location.href,
        });
      } catch (error) {
        console.log('Error sharing:', error);
      }
    } else {
      // Fallback: copy URL to clipboard
      navigator.clipboard.writeText(window.location.href);
      toast({
        title: "Link copied!",
        description: "Blog post URL has been copied to your clipboard",
      });
    }
  };

  // If no blog data, show 404 or loading state
  if (!blogData) {
    return <NotFound />;
  }

  return (
    <div className="min-h-screen">
      <Navbar />
      <main className="pt-20">
        {/* Header Section */}
        <section className="bg-gray-50 py-8 md:py-12">
          <div className="container-custom">
            <Link
              to="/portfolio/seo-blog-writer"
              className="inline-flex items-center text-gray-600 hover:text-gray-900 mb-6"
            >
              <ArrowLeft className="mr-2 h-4 w-4" /> Back to SEO Blog Writer
            </Link>
            
            <div className="max-w-4xl">
              <div className="flex items-center gap-4 text-sm text-gray-600 mb-4">
                <div className="flex items-center gap-1">
                  <Calendar className="h-4 w-4" />
                  <span>{new Date().toLocaleDateString()}</span>
                </div>
                <div className="flex items-center gap-1">
                  <Clock className="h-4 w-4" />
                  <span>5 min read</span>
                </div>
                <div className="flex items-center gap-1">
                  <User className="h-4 w-4" />
                  <span>AI Generated</span>
                </div>
              </div>
              
              <h1 className="text-3xl md:text-5xl font-bold mb-6 text-gray-900">
                {blogData.blogTitle}
              </h1>
              
              <div className="flex items-center gap-4">
                <div className="text-sm text-gray-600">
                  Generated by Small Group's AI Blog Writer
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* Blog Content */}
        <section className="py-8 md:py-12">
          <div className="container-custom">
            <div className="max-w-4xl mx-auto">
              <article className="prose prose-lg max-w-none">
                <div 
                  dangerouslySetInnerHTML={{ __html: blogData.blogContent }}
                  className="blog-content"
                />
              </article>
            </div>
          </div>
        </section>

        {/* Call to Action */}
        <section className="py-12 bg-gradient-to-br from-brand-purple to-brand-blue text-white">
          <div className="container-custom text-center">
            <h2 className="text-2xl md:text-3xl font-bold mb-4">
              Impressed by This AI-Generated Content?
            </h2>
            <p className="text-lg mb-8 max-w-2xl mx-auto opacity-90">
              This blog post was automatically generated by our SEO Blog Writer system. 
              Want to see how we can automate content creation for your business?
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Link
                to="/portfolio"
                className="inline-flex items-center justify-center px-6 py-3 bg-white text-brand-purple font-medium rounded-lg hover:bg-gray-100 transition-colors"
              >
                View More Projects
              </Link>
              <a
                href="https://cal.com/smallgrp/discovery"
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center justify-center px-6 py-3 bg-transparent border-2 border-white text-white font-medium rounded-lg hover:bg-white hover:text-brand-purple transition-colors"
              >
                Book a Discovery Call
              </a>
            </div>
          </div>
        </section>
      </main>
      <Footer />
    </div>
  );
};

export default BlogPost; 